import 'package:intl/intl.dart';
class Candidate{

  String ASSESSMENT_UUID;
  String ASSESSMENT_APPOINTMENT;
  String ASSESSMENT_APPOINTMENT_DATE;
  String ASSESSMENT_APPOINTMENT_TIME;
  String ASSESSMENT_ASSESSOR_FIRST;
  String ASSESSMENT_ASSESSOR_LAST;
  String ASSESSMENT_CANDIDATE_FIRST;
  String ASSESSMENT_CANDIDATE_LAST;
  String ASSESSMENT_CANDIDATE_EMAIL;
  String ASSESSMENT_CANDIDATE_NUMBER;
  String ASSESSMENT_ADDRESS_COMPANY;
  String ASSESSMENT_ADDRESS_ADDRESS1;
  String ASSESSMENT_ADDRESS_ADDRESS2;
  String ASSESSMENT_ADDRESS_TOWNCITY;
  String ASSESSMENT_ADDRESS_COUNTY;
  String ASSESSMENT_ADDRESS_POSTCODE;
  String ASSESSMENT_ADDRESS_COUNTRY;
  String ASSESSMENT_TITLE;
  String ASSESSOR_UUID;
  
  int ID;

  Candidate(String ASSESSMENT_UUID,String ASSESSMENT_APPOINTMENT,String ASSESSMENT_ASSESSOR_FIRST,String ASSESSMENT_ASSESSOR_LAST,String ASSESSMENT_CANDIDATE_FIRST,
  String ASSESSMENT_CANDIDATE_LAST,String ASSESSMENT_CANDIDATE_EMAIL,String ASSESSMENT_CANDIDATE_NUMBER,
  String ASSESSMENT_ADDRESS_COMPANY,String ASSESSMENT_ADDRESS_ADDRESS1,String ASSESSMENT_ADDRESS_ADDRESS2,
  String ASSESSMENT_ADDRESS_TOWNCITY,String ASSESSMENT_ADDRESS_COUNTY,String ASSESSMENT_ADDRESS_POSTCODE,
  String ASSESSMENT_ADDRESS_COUNTRY,String ASSESSMENT_TITLE,String ASSESSOR_UUID,int ID,String ASSESSMENT_APPOINTMENT_DATE,String ASSESSMENT_APPOINTMENT_TIME){

      this.ASSESSMENT_UUID = ASSESSMENT_UUID;
      this.ASSESSMENT_APPOINTMENT = ASSESSMENT_APPOINTMENT;
      this.ASSESSMENT_ASSESSOR_FIRST = ASSESSMENT_ASSESSOR_FIRST;
      this.ASSESSMENT_ASSESSOR_LAST = ASSESSMENT_ASSESSOR_LAST;
      this.ASSESSMENT_CANDIDATE_FIRST = ASSESSMENT_CANDIDATE_FIRST;
      this.ASSESSMENT_CANDIDATE_LAST = ASSESSMENT_CANDIDATE_LAST;
      this.ASSESSMENT_CANDIDATE_EMAIL = ASSESSMENT_CANDIDATE_EMAIL;
      this.ASSESSMENT_CANDIDATE_NUMBER = ASSESSMENT_CANDIDATE_NUMBER;
      this.ASSESSMENT_ADDRESS_COMPANY = ASSESSMENT_ADDRESS_COMPANY;
      this.ASSESSMENT_ADDRESS_ADDRESS1 = ASSESSMENT_ADDRESS_ADDRESS1;
      this.ASSESSMENT_ADDRESS_ADDRESS2 = ASSESSMENT_ADDRESS_ADDRESS2;
      this.ASSESSMENT_ADDRESS_TOWNCITY = ASSESSMENT_ADDRESS_TOWNCITY;
      this.ASSESSMENT_ADDRESS_COUNTY = ASSESSMENT_ADDRESS_COUNTY;
      this.ASSESSMENT_ADDRESS_POSTCODE = ASSESSMENT_ADDRESS_POSTCODE;
      this.ASSESSMENT_ADDRESS_COUNTRY = ASSESSMENT_ADDRESS_COUNTRY;
      this.ASSESSMENT_TITLE = ASSESSMENT_TITLE;
      this.ASSESSOR_UUID = ASSESSOR_UUID;
      this.ID = ID;
      this.ASSESSMENT_APPOINTMENT_DATE = ASSESSMENT_APPOINTMENT_DATE;
      this.ASSESSMENT_APPOINTMENT_TIME = ASSESSMENT_APPOINTMENT_TIME;
      
  }

   Candidate.fromJSON(Map json){
     String formattedDate = '';
     String strTime = '';

      String utcdate = json["ASSESSMENT_APPOINTMENT"];
      formattedDate = DateFormat('dd-MM-yyyy').format(DateTime.parse(utcdate));
      strTime = DateFormat('HH:mm:ss').format(DateTime.parse(utcdate));
      Candidate(
      ASSESSMENT_UUID = json["ASSESSMENT_UUID"],
      ASSESSMENT_APPOINTMENT = json["ASSESSMENT_APPOINTMENT"],
      ASSESSMENT_ASSESSOR_FIRST = json["ASSESSMENT_ASSESSOR_FIRST"],
      ASSESSMENT_ASSESSOR_LAST = json["ASSESSMENT_ASSESSOR_LAST"],
      ASSESSMENT_CANDIDATE_FIRST = json["ASSESSMENT_CANDIDATE_FIRST"],
      ASSESSMENT_CANDIDATE_LAST = json["ASSESSMENT_CANDIDATE_LAST"],
      ASSESSMENT_CANDIDATE_EMAIL = json["ASSESSMENT_CANDIDATE_EMAIL"],
      ASSESSMENT_CANDIDATE_NUMBER = json["ASSESSMENT_CANDIDATE_NUMBER"],
      ASSESSMENT_ADDRESS_COMPANY = json["ASSESSMENT_ADDRESS_COMPANY"],
      ASSESSMENT_ADDRESS_ADDRESS1 = json["ASSESSMENT_ADDRESS_ADDRESS1"],
      ASSESSMENT_ADDRESS_ADDRESS2 = json["ASSESSMENT_ADDRESS_ADDRESS2"],
      ASSESSMENT_ADDRESS_TOWNCITY = json["ASSESSMENT_ADDRESS_TOWNCITY"],
      ASSESSMENT_ADDRESS_COUNTY = json["ASSESSMENT_ADDRESS_COUNTY"],
      ASSESSMENT_ADDRESS_POSTCODE = json["ASSESSMENT_ADDRESS_POSTCODE"],
      ASSESSMENT_ADDRESS_COUNTRY = json["ASSESSMENT_ADDRESS_COUNTRY"],
      ASSESSMENT_TITLE = json["ASSESSMENT_TITLE"],
      ASSESSOR_UUID = json["ASSESSOR_UUID"],
      ID = json["ID"],
      ASSESSMENT_APPOINTMENT_DATE = formattedDate,
      ASSESSMENT_APPOINTMENT_TIME = strTime,
    );
      
  }
    

  Map toJson() {
    return {'ASSESSMENT_UUID': ASSESSMENT_UUID, 'ASSESSMENT_APPOINTMENT': ASSESSMENT_APPOINTMENT, 'ASSESSMENT_ASSESSOR_FIRST': ASSESSMENT_ASSESSOR_FIRST,
    'ASSESSMENT_ASSESSOR_LAST':ASSESSMENT_ASSESSOR_LAST,'ASSESSMENT_CANDIDATE_FIRST':ASSESSMENT_CANDIDATE_FIRST,'ASSESSMENT_CANDIDATE_LAST':ASSESSMENT_CANDIDATE_LAST,
    'ASSESSMENT_CANDIDATE_EMAIL':ASSESSMENT_CANDIDATE_EMAIL,'ASSESSMENT_CANDIDATE_NUMBER':ASSESSMENT_CANDIDATE_NUMBER,'ASSESSMENT_ADDRESS_COMPANY':ASSESSMENT_ADDRESS_COMPANY,
    'ASSESSMENT_ADDRESS_ADDRESS1':ASSESSMENT_ADDRESS_ADDRESS1,'ASSESSMENT_ADDRESS_ADDRESS2':ASSESSMENT_ADDRESS_ADDRESS2,'ASSESSMENT_ADDRESS_TOWNCITY':ASSESSMENT_ADDRESS_TOWNCITY,
    'ASSESSMENT_ADDRESS_COUNTY':ASSESSMENT_ADDRESS_COUNTY,'ASSESSMENT_ADDRESS_POSTCODE':ASSESSMENT_ADDRESS_POSTCODE,'ASSESSMENT_ADDRESS_COUNTRY':ASSESSMENT_ADDRESS_COUNTRY,
    'ASSESSMENT_TITLE':ASSESSMENT_TITLE,'ASSESSOR_UUID':ASSESSOR_UUID,'ID':ID};
  }

}