name: hea
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.3+1
  http: ^0.12.0+1
  shared_preferences: ^0.5.2
  screen: ^0.0.5
  intl: ^0.15.7
  contacts_service: ^0.2.6
  add_2_calendar: ^1.2.2
  device_calendar: ^0.1.2+2
  permission_handler: '^3.1.0'
  cached_network_image: ^0.8.0
  audioplayer: ^0.5.2
  chewie: ^0.9.7
  video_player: ^0.10.0+2
  auto_orientation: ^0.0.2
  flutter_youtube_view: ^1.1.4
  sqflite: ^1.1.5
  path_provider: 0.5.0+1
  camera: ^0.5.2+1
  path: ^1.6.2
  image_picker: ^0.6.0+9
  flutter_sound: ^1.4.2
  image: ^2.1.4
  flutter_video_compress: ^0.3.7+8





dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - assets/images/login_logo.png
    - assets/images/delete.png
    - assets/images/logout.png
    - assets/images/dropdown_icon.png
    - assets/images/check.png
    - assets/images/uncheck.png
    - assets/images/No.png
    - assets/images/Yes.png
    - assets/images/Bluetick.png
    - assets/images/Backbutton.png
    - assets/images/NoImageFound.png
    - assets/images/pause.png
    - assets/images/Play.png
    - assets/images/Stop.png
    - assets/images/camera.png
    - assets/images/Audio_record.png
    - assets/images/rerecord.png
    
    
    
  fonts:
     - family: SourceSansPro
       fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
    
  
     
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
